name: weather_forecast_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  flutter_dotenv: ^5.0.2

  go_router: ^6.0.1

  injectable: ^2.1.0
  flutter_riverpod: ^2.1.3
  riverpod_annotation: ^1.1.1

  dio: ^4.0.6
  retrofit: ^3.3.1

  json_annotation: ^4.7.0

  dartz: ^0.10.1
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  permission_handler: ^10.2.0

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  geocoding: ^2.0.5
  geolocator: ^9.0.2
 
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  riverpod_generator: ^1.1.1
  retrofit_generator: ^4.2.0
  json_serializable: ^6.5.4
  injectable_generator: ^2.1.3
  hive_generator: ^2.0.0
  mockito: ^5.3.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - config.env
    - assets/images/
    - assets/icons/
